# Generated by Django 3.1.7 on 2021-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20210315_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='open', max_length=260),
        ),
    ]
